### ISSUE TITLE
set_url

### ISSUE THREAD

**Issue by imSunnyk** [kazikame/251Project#4]
in spc sync spc set_url

what to do...

**Comment by yash-s20** [comment]
Hi! You'll have to setup a copy of this code on a server, or locally on your machine, and run manage.py, and the URL you need to feed would be the URL of this server. If it's on a separate server, that would be the IP address of this server. If it's your local computer, then the URL would be http://127.0.0.1:8000. You can find the port and IP settings in the settings.py file.
The codebase is old, and it was primarily made as a student project. Hence the lack of documentation. However, if you plan to use this professionally, please contact one of us contributors :). Thanks!

**Comment by imSunnyk** [comment]
Which version of django have you used in this project?
